name: Trigger Build

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: amd64
          - os: ubuntu-24.04-arm
            platform: arm64
    runs-on: ${{matrix.os}}
    steps:
      - name: Free up disk space
        run: |
          sudo swapoff -a || true
          sudo rm -rf /opt/ghc /usr/local/.ghcup || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /opt/hostedtoolcache/go /opt/az /opt/microsoft
          sudo rm -rf /usr/share/miniconda /home/runner/.rustup /home/packer/.rustup /home/runneradmin/.rustup
          sudo rm -rf /etc/skel/.rustup /opt/hostedtoolcache/node /opt/google-cloud-sdk
          sudo rm -rf /usr/share/az_* /opt/google /usr/lib/firefox /usr/local/aws-*
          sudo rm -rf /usr/libexec/gcc /opt/actionarchivecache /var/lib/mysql /usr/local/n
          sudo rm -rf /swapfile || true
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet /usr/share/swift
          sudo rm -rf /usr/local/share/boost /usr/local/share/powershell
          sudo rm -rf /usr/lib/google-cloud-sdk /usr/lib/jvm
          sudo rm -rf /usr/local/graalvm /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/lib/dotnet /usr/lib/php /usr/share/mysql
          sudo rm -rf /usr/lib/llvm-*
          sudo rm -rf /usr/lib/mono
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Get large directories
        run: |
         sudo du -xh --max-depth=3 / 2>/dev/null | sort -rh | head -40 || true
