name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install dependencies
        run: pip install requests

      - name: Check format
        run: |
          python3 -c "import requests; url = 'https://twintaillauncher.app/'; r = requests.get(url, allow_redirects=False); print(r.ok)"
